_source_util() {
    source "$HOME/.config/zsh/initial/util.zsh"
}

export ZSH_CONFIG_DIR="$HOME/.config/zsh"

if [ -x "$(command -v tmux)" ] && [ -z "${TMUX}" ]; then
   exec tmux new-session -A -s ${USER} >/dev/null 2>&1
fi

setopt autocd
setopt extendedglob
setopt nomatch
setopt menucomplete
setopt interactive_comments

stty stop undef
zle_highlight=('paste:none')

unsetopt BEEP

_source_util
_set_log_verbocity_warning

local initial_folder="${ZSH_CONFIG_DIR}/initial"

local sources=(
    "env.zsh"
    "zplug.zsh"
    "completion.zsh"
)


for file in "${sources[@]}"; do
    _safe_source "$initial_folder/$file"
done


_safe_source "$HOME/.zshlocal"


for file in $(find "$ZSH_CONFIG_DIR/integrations" -type f -name '*.zsh' | sort); do
    _safe_source "$file"
done


local message="Today is the best day"
if command -v fortune &> /dev/null; then
    message="$(fortune)"
fi
if command -v cowsay &> /dev/null; then
    message="$(cowsay $message)"
fi
if command -v lolcat &> /dev/null; then
    echo $message | lolcat
    echo
    echo
else
    echo $message
    echo
    echo
fi

if command -v fastfetch &> /dev/null; then
    fastfetch
fi

if command -v direnv &> /dev/null; then
    eval "$(direnv hook zsh)" 
fi

if command -v starship &> /dev/null; then
    eval "$(starship init zsh)"
elif [ -f ~/.p10k.zsh ]; then
    source ~/.p10k.zsh
fi
