[project]
name = "arch config"
authors = ["Alexander Ivanov"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[dependencies]
python = ">=3.13"
typing-extensions = ">=4.13.2,<5"

[pypi-dependencies]
syncall = { version = "*", extras = ["notion", "tw"] }
